# GitHub Actions workflow for astrometric calibration (ac) testing

name: AC Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  INDEX_CACHE_VERSION: "v1"
  ASTROMETRY_INDEX_DIR: ~/.astrometry/data

jobs:
  astrometrynet:
    uses: ./.github/workflows/astrometrynet-venv.yml

  test:
    name: Astrometric Calibration Test Suite
    needs: [astrometrynet]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Restore cached astrometry index files
        uses: actions/cache/restore@v4
        id: restore-index
        with:
          key: astrometry-index-${{ env.INDEX_CACHE_VERSION }}
          path: ${{ env.ASTROMETRY_INDEX_DIR }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y astrometry.net netpbm

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e .[test,recommended]

      - name: Run astrometric calibration tests with coverage
        run: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)
          pytest tests/ -v --maxfail=3 --disable-warnings --cov=catch_analysis_tools --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
