# GitHub Actions workflow for caching astrometry.net index files
on:
  workflow_call:

env:
  INDEX_CACHE_VERSION: "v1"
  ASTROMETRY_INDEX_DIR: ~/.astrometry/data

jobs:
  astrometrynet:
    name: Download and cache astrometry.net index files
    runs-on: ubuntu-latest
    steps:
      - name: Set up index file directory
        run: mkdir -p ${{ env.ASTROMETRY_INDEX_DIR }}

      - name: Check for cached index files
        id: cache
        uses: actions/cache/restore@v4
        with:
          key: astrometry-index-${{ env.INDEX_CACHE_VERSION }}
          path: ${{ env.ASTROMETRY_INDEX_DIR }}

      - name: Download index files
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ env.ASTROMETRY_INDEX_DIR }}
          wget http://data.astrometry.net/4200/index-4200.fits
          wget http://data.astrometry.net/4200/index-4201.fits
          wget http://data.astrometry.net/4200/index-4202.fits
          wget http://data.astrometry.net/4200/index-4203.fits

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: astrometry-index-${{ env.INDEX_CACHE_VERSION }}
          path: ${{ env.ASTROMETRY_INDEX_DIR }}
